package mazin.certification.classes;

/*
The constructor of Employee must call its super constructor, the constructor of Person.
A default, no-arg constructor is generated by the compiler only if the class has no constructor defined explicitly.
*/

/*
public class Person {
	String name = "No name";
	public Person(String nm){
		name = nm;
	}
}
class Employee extends Person{
	String empID = "0000";
	public Employee(String id){//Implicit super constructor Person() is undefined. Must explicitly invoke another constructor
		empID = id;
	}
}
====================================================
public class Person {
	String name = "No name";
	public Person(String nm){
		name = nm;
	}
	public Person(){
	}
}
class Employee extends Person{
	String empID = "0000";
	public Employee(String id){//Works fine Notice the No-args super constructor
		empID = id;
	}
}
====================================================
public class Person {
	String name = "No name";
	public Person(){
	}
}
class Employee extends Person{
	String empID = "0000";
	public Employee(String id){//Works fine Notice the No-args super constructor
		empID = id;
	}
}
*/
